### ISSUE TITLE
Extended processing times: calc_attributes_sites_approx

### ISSUE THREAD

**Issue by HunterGleason** [MiKatt/openSTARS#14]
Since the most recent update of the openSTARS package (1.2.0) I have found that when running the calc_attributes_sites_approx() command on both observed and particularity predicted site data, processing times are orders of magnitude longer than in the previous package version (same script). I am curious what changes may have led to the longer processing times in the updated openSTARS package?

**Comment by MiKatt** [comment]
Thanks for this comment. I will look into it soon as I am preparing so other updates and will come back to you.

**Comment by MiKatt** [comment]
I compared the two releases (https://github.com/MiKatt/openSTARS/compare/v1.1.0...v1.2.0#diff-a2f3d86e1cc1c18e1c9db713cddb1523) and cannot find anything that might cause this increase in processing time; it should even be a bit faster as it uses now a less complex query.
Did you change anything else on your system (R or Grass version)?

**Comment by HunterGleason** [comment]
Thanks for looking into this. It could be an issue on my end as I think I am running a different version of R (now running 3.6.3). I believe I am using the same GRASS version however (7.6.0). It does finish in a very reasonable time (about an hour for Bowron watershed, BC), so not really an issue. Just seemed like it was taking longer than before the update.

Also I was getting an error when I set calc_basin_area to FALSE, it went something like “in cnames2 %in% cnames can’t find cnames”, but don’t get this error when calc_basin_area is set to TRUE?

Thanks,
Hunter
