### ISSUE TITLE
Error thrown during correct_compl_confluences

### ISSUE THREAD

**Issue by HunterGleason** [MiKatt/openSTARS#15]
When running the correct_compl_confluences function GRASS throws error:

Error in execGRASS("v.to.db", flags = c("quiet"), parameters = list(map = "streams_v",  : 
  The command:
v.to.db --quiet map=streams_v option=length type=line columns=length_new
produced an error (1) during execution:
ERROR: Column <length_new> exists. To overwrite, use the --overwrite flag

This may be a grass78 issue?

**Comment by MiKatt** [comment]
This is indeed a GRASS 7.8 issue because v.to.db works a bit differenetly now. This is fixed in the dev branch. (Note that there might be other issues in that branch.)
