### ISSUE TITLE
GeoTIFF Projection

### ISSUE THREAD

**Issue by jakehosen** [MiKatt/openSTARS#20]
I am trying to load DEM's from the USGS one meter dataset (e.g., https://www.sciencebase.gov/catalog/item/5eacf66d82cefae35a24e88b).

I am able to succesfully execute setup_grass_environment() and then I am able to use import_data() to load the DEM and sites. However when I use the command
`dem <- readRAST("dem", ignore.stderr = TRUE)`

I get the following error message that indicates WKT projection strings aren't being properly formatted. I have no issues working with or opening these files in GRASS and QGIS.

`Error in sp::CRS(getLocationProj()) : 
  PROJ4 argument-value pairs must begin with +: PROJCS["NAD83 / UTM zone 16N",
    GEOGCS["NAD83",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6269"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4269"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-87],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","26916"]]`

**Comment by MiKatt** [comment]
I cannot reproduce the error with the linked dem. I only get warnings during `setup_grass_environment`:

```
Warning messages:
1: In getProjectionRef(x, OVERRIDE_PROJ_DATUM_WITH_TOWGS84 = OVERRIDE_PROJ_DATUM_WITH_TOWGS84,  :
  Discarded datum North_American_Datum_1983 in Proj4 definition: +proj=utm +zone=16 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs,
 but +towgs84= values preserved
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj = prefer_proj) :
  Discarded datum Unknown based on GRS80 ellipsoid in Proj4 definition
```

and during plotting with `tmap`:

```
In sp::proj4string(obj) :
  CRS object has comment, which is lost in output
```

They are related to the change from proj4 to proj>=6.

Maybe updating all related packages  particularly `sp` as well as GDAL and PROJ helps.

**Comment by jakehosen** [comment]
Thank you for the help.

The problem appears to have been GDAL. I had a fresh install of QGIS LTS, which was installing an older version of GDAL. I'm a mac user and have had problems in the past with GDAL and homebrew, but I was able to fix the problem by installing the latest GDAL complete framework released by KyngChaos: https://www.kyngchaos.com/software/frameworks/.
