### ISSUE TITLE
Error in derive_streams

### ISSUE THREAD

**Issue by mjciupak** [MiKatt/openSTARS#21]
Hello! I am trying to use use the derive streams function and running into this error message: 

`Error in parseGRASS(cmd, legacyExec = legacyExec) 
The command r.stream.order --interface-description
could not be run (127), and produced the error message: /bin/sh: r.stream.order: command not found`

Even after installing and reinstalling the add on in GRASS 7.8.4. Any help is appreciated! 
note: I tried running the command r.stream.order within GRASS and it says the file type in not ’CELL” Would this have anything to do with it?

**Comment by MiKatt** [comment]
Maybe it needs a restart after reinstalling the addons in GRASS.

If that does not help, could you please try to run the following in GRASS standalone and post any error or warning messages:
1. r.watershed with elevation = "dem",  accumulation = "accums"
2. r.stream.extract" with elevation = "dem", accumulation = "accums", 
      threshold = your_accum_threshold, d8cut = 100000, stream_length = your_min_stream_length, 
      stream_raster = "streams_r", direction = "dirs"
3.  "r.stream.order", flags = "z, m", stream_rast = "streams_r", direction = "dirs", elevation = "dem", accumulation = "accums", 
    stream_vect = "streams_v"

**Comment by mjciupak** [comment]
Yes, r.watershed and r.stream.extract completed without any errors. r.stream.order came back with the error: 
`ERROR: Raster map <paint_river_5m@PERMANENT> is not of type 'CELL'`

**Comment by MiKatt** [comment]
Could you send me some (small) test data please to check if there is something wrong with the dem?

**Comment by mjciupak** [comment]
Switched from Mac to Linux and have it working now. Thank you for your help!
