### ISSUE TITLE
ERROR 1: PROJ: proj_create_geographic_crs: SQLite error on SELECT

### ISSUE THREAD

**Issue by jakehosen** [MiKatt/openSTARS#22]
I'm trying to run the tutorial using Windows 10 with Grass 7.8, R 4.0.5 running openSTARS_1.2.2  and rgrass7_0.2-6.

When I try to run the setup_grass_environment step in the tutorial I get the following error. It appears to be related to sqlite, but I can't figure out how to fix it.

ERROR 1: PROJ: proj_create_geographic_crs: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name

**Comment by MiKatt** [comment]
Sorry for the late reply. I am trying to reproduce this error and will come back as soon as possible. Let me know if there are any news.

**Comment by MiKatt** [comment]
I was able to reproduce the same problem on my Windows 10 with GRASS 7.8.5. After installing GRASS 7.6.1 standalone alongsite the newer version, the problem was gone. Also, when I uninstall GRASS 7.6 it still works.
Does this help on your computer?

**Comment by jakehosen** [comment]
Yes, this solves the problem! Thank you again!
