### ISSUE TITLE
Connecting to GRASS from QGIS installation

### ISSUE THREAD

**Issue by FNRobinne** [MiKatt/openSTARS#23]
Hi,

I have QGis 3.16.4 with GRASS 7.8.5 installed on a Windows 10 machine. How can I run GRASS from R/openSTARS with this setup?

Thanks

**Comment by MiKatt** [comment]
Please give some more details what is not working.
You just need to specify the correct path to GRASS (`gisBase`) when calling `setup_grass_environment`.

**Comment by FNRobinne** [comment]
Here is the way I set it up:
`library(rgrass7)`
`Sys.setenv(PATH=paste0("C:/Program Files/QGIS 3.16/bin",";", Sys.getenv("PATH")))`
`initGRASS(gisBase = "c:/Program Files/QGIS 3.16/apps/grass/grass78", 
          home = tempdir(),
          gisDbase = "C:/GRASSDB",
          override = T)`

When I run it, I get the following error message:
`Error : XML content does not seem to be XML: ''
In addition: Warning message:
In system(cmd0, intern = TRUE) :
  running command 'g.proj.exe --interface-description' had status 5
Error in parseGRASS(cmd, legacyExec = legacyExec) : g.proj not parsed`

**Comment by MiKatt** [comment]
This seems to be a general Windows - GRASS - R problem not specifically related to `openSTARS`.
I found this when searching for your error message:
[https://gis.stackexchange.com/questions/351637/problem-running-grass-with-r](https://gis.stackexchange.com/questions/351637/problem-running-grass-with-r) and this
[https://gis.stackexchange.com/questions/377481/unable-to-execute-grass-7-8-in-rstudio](https://gis.stackexchange.com/questions/377481/unable-to-execute-grass-7-8-in-rstudio)
Does that help?

Please note that there is no need to call `initGRASS` before `setup_grass_environment` as it is called within (however, I suppose, the error would still persist).

I run GRASS standalone on Windows 10 and do not have any problems. I think it could be installed next to the one from QGIS, even though this would not be the most elegant option.

**Comment by FNRobinne** [comment]
Thank you. I might just install a standalone version of GRASS to avoid fiddling with the environment variables. Thank you.
