### ISSUE TITLE
Importing prediction sites

### ISSUE THREAD

**Issue by diamondr88** [MiKatt/openSTARS#26]
Hello,

I've been using OpenStars with success when just using site data. However, I've come to a point where I need to also load in prediction sites into the environment. I keep getting errors. I've made sure that all the projections are correct, and I've tried pretending my sites.shp is my prediction file (as I know it works as a sites file) but it still doesn't load. This is my code and the error:

import_data(dem = dem_path, sites = sites_path, pred_sites = pred_sites)

Loading DEM into GRASS as 'dem' ...
Loading sites into GRASS as 'sites_o' ...
Loading preditions sites into GRASS as 'final preds 2_o' ...
No streams available, skipping.

Warning message:
In system(syscmd, intern = intern, ignore.stderr = ignore.stderr,  :
  running command 'v.import.bat --overwrite --quiet input="C:/Users/Rowena/Documents/SSN documents/Model outputs/final preds 2.shp" output="final preds 2_o" snap=-1 extent=region' had status 1

**Comment by MiKatt** [comment]
I am not sure if it is so easy, but could you try file names without spaces?

**Comment by diamondr88** [comment]
Thanks for the reply - I have just given that a go and I get the same error unfortunately!

**Comment by aaronRcarr** [comment]
Hello, I was wondering if there was a solution found to this issue?
