### ISSUE TITLE
calc_prediction_sites {openSTARS} one site per segment/edge

### ISSUE THREAD

**Issue by KGBrennan** [MiKatt/openSTARS#33]
Hi, is it possible to use calc_prediction_sites {openSTARS} to generate one site placed on the center of each edge or stream segment? 

Thanks.

**Comment by MiKatt** [comment]
Sorry, so far it is only possible to distibute the sites with approximatelly the same distance between each other.
If you have a look at the code of the fuction, you may come up with a looping algorithm yourself.
If you have any questions about the details for that, just let me know

**Comment by KGBrennan** [comment]
Thanks,

A work around is used was to export edges as spatial lines in R and generate centroid points for each edge, then when they are snaped they are usually close enough yet might not work for all river networks. Should double check edges and developed center prediction points.
________________________________
