### ISSUE TITLE
Get stream network structure

### ISSUE THREAD

**Issue by alaindanet** [MiKatt/openSTARS#8]
Hi,

thank you again for your amazing package.

I would like to know at which distance up and down my observation points are from obtacles such as dams, etc... It seems to me that I need to extract the topology of my stream network to do that.

It seems that this information is in the `netID` and the various netID*.dat present in the SSN object.

Are the informations about the stream network topology can be extracted on the form of an igraph object for example?

Thank you very much.

**Comment by MiKatt** [comment]
Yes, this information is in the netID and the netID*.dat in the SSN object; it's the format that the SSN package requires. However, it might be easier to get the information from the GRASS DB object edges (not the exported shape file). There are the columns stream, prev_str01, prev_str02 and next_str, which give the ID of the stream segment, the IDs of the two ones flowing into this segment and the ID of the one that this segment flows into. They are derived with r.stream.order (and adjusted in correct_compl_confluences). I have not worked with igraph objects yet.

For a future version a function with the functionality you describe might be useful. 
Thanks for your testing and the suggestions!

**Comment by jsta** [comment]
There are some functions to work with igraph and stream networks in the `streamnet` package https://github.com/jsta/streamnet

**Comment by alaindanet** [comment]
Thank you very much for the options, they look great!

I will come back to you as soon as I have tested them.
